<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cd" nsURI="it.unibz.udig/omtg/cd" nsPrefix="cd">
  <eClassifiers xsi:type="ecore:EClass" name="OMTClassDiagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//OMTClass" containment="true" eOpposite="#//OMTClass/diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
        eType="#//OMTRelationship" containment="true" eOpposite="#//OMTRelationship/diagram"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OMTClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagram" eType="#//OMTClassDiagram"
        eOpposite="#//OMTClassDiagram/classes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&lt; ... >"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraint" eType="#//Rectangle"
        defaultValueLiteral="0,0,50,50"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingRelations" upperBound="-1"
        eType="#//OMTRelationship" eOpposite="#//OMTRelationship/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingRelations" upperBound="-1"
        eType="#//OMTRelationship" eOpposite="#//OMTRelationship/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//ClassAttribute" containment="true" eOpposite="#//ClassAttribute/omtclass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//ClassOperation" containment="true" eOpposite="#//ClassOperation/omtclass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="#//Multiplicity"
        defaultValueLiteral="*"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassOperation" eSuperTypes="#//ClassElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="omtclass" eType="#//OMTClass"
        eOpposite="#//OMTClass/operations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassAttribute" eSuperTypes="#//ClassElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="omtclass" eType="#//OMTClass"
        eOpposite="#//OMTClass/attributes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OMTConventionalClass" eSuperTypes="#//OMTClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="OMTGeoreferencedClass" eSuperTypes="#//OMTClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="OMTGeoFieldClass" eSuperTypes="#//OMTClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="representation" lowerBound="1"
        eType="#//OMTGeoFieldClassKind" defaultValueLiteral="Triangular Irregular Network"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OMTGeoObjectGeometryClass" eSuperTypes="#//OMTClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="representation" eType="#//OMTGeoObjectGeometryClassKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OMTGeoObjectTopologyClass" eSuperTypes="#//OMTClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="representation" eType="#//OMTGeoObjectTopologyClassKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OMTGeneralization" eSuperTypes="#//OMTRelationship">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//GeneralizationKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="total" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OMTRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagram" eType="#//OMTClassDiagram"
        eOpposite="#//OMTClassDiagram/relations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//OMTClass"
        eOpposite="#//OMTClass/incomingRelations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//OMTClass"
        eOpposite="#//OMTClass/outgoingRelations"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bendpoints" upperBound="-1"
        eType="#//Point"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//OMTRelationshipType"
        defaultValueLiteral="Simple association"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rule" eType="#//SpatialIntegrityRule"
        defaultValueLiteral="NONE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OMTAggregation" eSuperTypes="#//OMTRelationship">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="spatial" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Multiplicity">
    <eLiterals name="NONE" literal="*"/>
    <eLiterals name="ZERO_MORE" value="1" literal="0..*"/>
    <eLiterals name="ONE" value="2" literal="1"/>
    <eLiterals name="ONE_MORE" value="3" literal="1..*"/>
    <eLiterals name="ZERO_ONE" value="4" literal="0..1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OMTGeoFieldClassKind">
    <eLiterals name="TRIANGULAR_IRREGULAR_NETWORK" literal="Triangular Irregular Network"/>
    <eLiterals name="ISOLINE" value="1" literal="Isoline"/>
    <eLiterals name="PLANAR_SUBDIVISION" value="2" literal="Planar Subdivision"/>
    <eLiterals name="TESSELATION" value="3" literal="Tesselation"/>
    <eLiterals name="SAMPLING" value="4" literal="Sampling"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OMTGeoObjectGeometryClassKind">
    <eLiterals name="POINT" literal="Point"/>
    <eLiterals name="LINE" value="1" literal="Line"/>
    <eLiterals name="POLYGON" value="2" literal="Polygon"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OMTGeoObjectTopologyClassKind">
    <eLiterals name="UNIDIRECTIONAL_LINE" literal="Unidirectional Line"/>
    <eLiterals name="BIDIRECTIONAL_LINE" value="1" literal="Bidirectional Line"/>
    <eLiterals name="NODE" value="2" literal="Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OMTRelationshipType">
    <eLiterals name="SIMPLE_ASSOCIATION" literal="Simple association"/>
    <eLiterals name="SPATIAL" value="1" literal="Spatial"/>
    <eLiterals name="ARC_NODE_NETWORK" value="2" literal="Arc Node Network"/>
    <eLiterals name="ARC_ARC_NETWORK" value="3" literal="Arc Arc Network"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Rectangle" instanceClassName="org.eclipse.draw2d.geometry.Rectangle"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Point" instanceClassName="org.eclipse.draw2d.geometry.Point"/>
  <eClassifiers xsi:type="ecore:EEnum" name="SpatialIntegrityRule">
    <eLiterals name="NONE"/>
    <eLiterals name="TOUCH" value="1"/>
    <eLiterals name="IN" value="2"/>
    <eLiterals name="CROSS" value="3"/>
    <eLiterals name="OVERLAP" value="4"/>
    <eLiterals name="DISJOINT" value="5"/>
    <eLiterals name="ADJACENT_TO" value="6"/>
    <eLiterals name="COINCIDE" value="7"/>
    <eLiterals name="CONTAIN" value="8"/>
    <eLiterals name="NEAR" value="9"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GeneralizationKind">
    <eLiterals name="DISJOINT"/>
    <eLiterals name="OVERLAP" value="1"/>
  </eClassifiers>
</ecore:EPackage>
